### ISSUE TITLE
Failed to find match for field 'ambient'

### ISSUE THREAD

**Issue by AhmedBaza1** [brytsknguyen/slict#17]
Hi, I'm trying to use BpearlToOuster node to use the hilti dataset on Fast_lio, I get this error when I run it  ``` Failed to find match for field 'ambient'. ``` 
![image](https://github.com/brytsknguyen/slict/assets/85301677/b1530a92-0ff0-46d3-ab49-cb5984fbe859)

**Comment by brytsknguyen** [comment]
Hi,

It's because fast_lio has the ambient defined in the pointouster
https://github.com/hku-mars/FAST_LIO/blob/5d9dc72523f465633d57bb9c3ac4e3f4fdaffb4c/src/preprocess.h#L55

You can uncomment this line in slict and the warning should go away
https://github.com/brytsknguyen/slict/blob/40b1262ff8c5a07b710ed54b9940c395f394ae62/include/utility.h#L125

**Comment by AhmedBaza1** [comment]
Hi. 
Thank you for the fast reply, that took care of it
