### ISSUE TITLE
About NTU VIRAL

### ISSUE THREAD

**Issue by whw-create** [brytsknguyen/slict#18]
Hi, recently i tried to use your NTU VIRAL dataset, but i found that there are something wrong about the imu's timestamp, as i printed some part below:
![image](https://github.com/brytsknguyen/slict/assets/92702274/40a35bac-a15d-46b0-9109-f0a076c9ac5b)
do i need to adjust the timestamp by myself using the IMU rate in your paper, 400 or 385Hz?

**Comment by whw-create** [comment]
the sequence i used was rtp_03

**Comment by brytsknguyen** [comment]
Hi,

Thanks for notifying the issue. The IMU timestamps seem uneven. It seems like the publisher could only read the buffer at 5ms, hence two samples are published quite close to each other. Its nominal value is 400Hz so the interval should be about 2.5ms. 

For most applications I don't have an issue since the time sequence is still causal. If you need strict time stamp maybe you can drop half the IMU data. Or maybe write a script to restamp the IMU samples using the sampling period dt = (t_IMU_last - t_IMU_first)/(total_IMU-1).

**Comment by whw-create** [comment]
> Hi,
> 
> Thanks for notifying the issue. The IMU timestamps seem uneven. It seems like the publisher could only read the buffer at 5ms, hence two samples are published quite close to each other. Its nominal value is 400Hz so the interval should be about 2.5ms.
> 
> For most applications I don't have an issue since the time sequence is still causal. If you need strict time stamp maybe you can drop half the IMU data. Or maybe write a script to restamp the IMU samples using the sampling period dt = (t_IMU_last - t_IMU_first)/(total_IMU-1).

thanks, i try to set the timestamp using last imu stamp and imu rate when two imu's stamp are too close.

**Comment by whw-create** [comment]
Hello, recently I attempted to run eee_01 using the FAST-LIO configuration provided on your GitHub page and calculate the ATE using evo. However, I couldn't obtain results similar to those presented in the SLICT paper. Could you please advise me on the possible reasons for this? 
In addition, I would like to know what metrics you use in your paper, whether it's RMSE, mean, or something else? Below is a screenshot of the results from evo.
![image](https://github.com/brytsknguyen/slict/assets/92702274/9968296e-6993-48e2-8b0c-9c536b124fc3)
