### ISSUE TITLE
Hi, maybe your new Slict2 paper have some typos 

### ISSUE THREAD

**Issue by lfwin** [brytsknguyen/slict#20]
Hi, thank you sharing such excellent work. Below maybe some typos,
1,  Equation (17), IMU acceleration observation model
R_t shoud R_t^-1 and '...+ a^{wave}_t' should be '...- a^{wave}_t'.

2 Equation (26), 
.....J_r^{-1}(-d_{j+1}) should be .....J_r^{-1}(-d_{j+1}) * R_{i + j + 1}.

3 Equation (32)
This have the same problem as above item 2.

**Comment by brytsknguyen** [comment]
Hi, 

Equation (17) has a typo as u pointed out. I'll correct it in the preprint version.

For equation (26) and (32) I think R_{i + j + 1} should not show up. Are you comparing my equations with equation (47) in [Sommer's paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Sommer_Efficient_Derivative_Computation_for_Cumulative_B-Splines_on_Lie_Groups_CVPR_2020_paper.pdf)? 

I think in Sommer paper there is a mistake in (47). By the definition in eq (24) of the same paper we should have ddj/dRj = Jr^{-1}(dj) instead of ddj/dRj = Jr^{-1}(dj)Rj^T.

**Comment by lfwin** [comment]
I followed the derivation in [Sommer's paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Sommer_Efficient_Derivative_Computation_for_Cumulative_B-Splines_on_Lie_Groups_CVPR_2020_paper.pdf)  as follows, please help me verify which step is not correct?
`
dj = Log(R_{j-1}^{-1} * Exp(phi) * Rj} and
ddj/dRj = \lim_{phi \to 0}(Log(R_{j-1}^{-1} * Exp(phi) * Rj} - dj)/dphi 
            = \lim_{phi \to 0}(Log(R_{j-1}^{-1} * Rj * Exp(Rj^{-1} * phi) } - dj)/dphi , this is based on equation (5) in Sommer's paper
            = \lim_{phi \to 0}(dj + Jr^{-1}(dj) * Rj^{-1} * phi  - dj)/dphi, this is based on equation (9) in Sommer's paper
            = Jr^{-1}(dj) * Rj^{-1} , which is equation (47) in Sommer's paper
`

**Comment by brytsknguyen** [comment]
I found the issue. Sommer uses the left jacobian rule. Their equation (47) is correct and your derivative is also correct.

However in SLICT I use the right jacobian rule. The full definition is given in [Sola](https://arxiv.org/pdf/1812.01537)'s paper here

![image](https://github.com/brytsknguyen/slict/assets/13504903/ba44c4de-9607-4ca3-bba5-2107c9c98630)

I have checked the theory and implementation and there is no problem. As long as we apply the correct [localparameterization](https://github.com/brytsknguyen/slict/blob/3edbfa66583f9a0503ebd0ea73566623064acdd5/include/basalt/spline/ceres_local_param.hpp#L152) both left and right jacobian rules are ok. Just to be sure I also did a check between ceres autodiff and the analytic jacobian and they are exactly the same.

![image](https://github.com/brytsknguyen/slict/assets/13504903/289d0ef3-fbac-4dcc-bd59-129cdf0ed9f8)
